### ISSUE TITLE
Handle more fractionals than 1/2 when fixing house numbers

### ISSUE THREAD

**Issue by trescube** [mapbox/pt2itp#294]
The current code only removes the `1/2` fractional from the `number` property:

`feat.properties.number = feat.properties.number.replace(/\s1\/2$/, '');`

There are many other fractionals in the data such as `1/4`, `2/3`, and `3/4`.  

Additionally, I've seen house numbers formatted like `10-1/2` so the whitespace character in the regex is not sufficient.

**Comment by ilissablech** [comment]
Closing as we now handle stripping other fractionals in the data such as 1/4, 2/3, and 3/4 from house numbers formatted like both 10 1/2 & 10-1/2.
