### ISSUE TITLE
Refactor display text and synonym generation

### ISSUE THREAD

**Issue by lizziegooding** [mapbox/pt2itp#494]
## Context

While investigating a bug where we were emitting equivalent synonyms in our final address clusters, I did a deep dive into how we process the original names we get from component address and network features and create synonyms. There's a lot here that's leftover from when we hadn't ported much of the code base to Rust or introduced more intelligent token handling. We should fix this duplication issue and make our name process pipeline simpler and more robust. See PR for next steps.

cc @miccolis @ingalls @samely

**Comment by ingalls** [comment]
@lizziegooding can we expand the scope slightly to handle proper titlecasing of minors at the beginning of a text value?

Example:

```
a 10, Germany
```

should be 

```
A 10, Germany
```

My guess is that an `en` language code is potentially being passed in the `titlecase.js` module to https://github.com/mapbox/title-case, if this is the case we should adjust the behavior of how minors are capitalized to only be lowercased if not the first token in a text value.

**Comment by lizziegooding** [comment]
Done in https://github.com/mapbox/pt2itp/releases/tag/25.0.0 and https://github.com/mapbox/pt2itp/releases/tag/v26.0.0
